_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "model_cache/COCO_faster_rcnn_R_50_FPN_3x.pkl"
  BACKBONE:
    NAME: "build_resnet_superposition_fpn_backbone"
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 7
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("Daytime-sunny_train",)
  #  TEST: ("Daytime-sunny_valid","Dusk-rainy_valid","Daytime-Foggy_valid","Night-rainy_valid")
  TEST: ("Night-Sunny_valid",)

DATALOADER:
  NUM_WORKERS: 22
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.005
  STEPS: (82000, 94000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 1000
OUTPUT_DIR: "runs/train/Default/Generalization"
INPUT:
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 500