_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "model_cache/COCO_faster_rcnn_R_50_FPN_3x.pkl"
  BACKBONE:
    NAME: "build_resnet_superposition_fpn_backbone"
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 1
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("SIM10K_train",)
  TEST: ("SIM10K_valid",)
DATALOADER:
  NUM_WORKERS: 22
SOLVER:
  IMS_PER_BATCH: 38
  BASE_LR: 0.02
  STEPS: (41000, 45000)
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 1000
OUTPUT_DIR: "runs/train/Default/SIM10K_debug"
INPUT:
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 250